//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from L20nParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IL20nParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class L20nParserBaseListener : IL20nParserListener
{
    /// <summary>
    /// Enter a parse tree produced by <see cref="L20nParser.document"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterDocument([NotNull] L20nParser.DocumentContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="L20nParser.document"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitDocument([NotNull] L20nParser.DocumentContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="L20nParser.entity"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterEntity([NotNull] L20nParser.EntityContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="L20nParser.entity"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitEntity([NotNull] L20nParser.EntityContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="L20nParser.entityName"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterEntityName([NotNull] L20nParser.EntityNameContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="L20nParser.entityName"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitEntityName([NotNull] L20nParser.EntityNameContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="L20nParser.entityValue"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterEntityValue([NotNull] L20nParser.EntityValueContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="L20nParser.entityValue"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitEntityValue([NotNull] L20nParser.EntityValueContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="L20nParser.entityProperty"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterEntityProperty([NotNull] L20nParser.EntityPropertyContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="L20nParser.entityProperty"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitEntityProperty([NotNull] L20nParser.EntityPropertyContext context) { }
    /// <summary>
    /// Enter a parse tree produced by <see cref="L20nParser.misc"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void EnterMisc([NotNull] L20nParser.MiscContext context) { }
    /// <summary>
    /// Exit a parse tree produced by <see cref="L20nParser.misc"/>.
    /// <para>The default implementation does nothing.</para>
    /// </summary>
    /// <param name="context">The parse tree.</param>
    public virtual void ExitMisc([NotNull] L20nParser.MiscContext context) { }

    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
    /// <inheritdoc/>
    /// <remarks>The default implementation does nothing.</remarks>
    public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}