export default {
  ACCOUNT: 'Account',
  AUTHENTICATION: 'Authentication',
  ACTIVITY: 'Activity',
  CONTACT: 'Contact',
  INTEGRATION: 'Integration',
  LEAD: 'Lead',
  LEADADDRESS: 'LeadAddress',
  OPPORTUNITY: 'Opportunity',
  OPPORTUNITYCONTACT: 'OpportunityContact',
  TICKET: 'Ticket',
  TICKETACTIVITY: 'TicketActivity',
  USERACTIVITY: 'UserActivity',
  ADDRESS: 'Address',
  HISTORY: 'History',
};
